### ISSUE TITLE
Add checks for unsupported Cliquet protocol version.

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/kinto.js#40]
### Goals

The client should:

- check that the protocol version defined by the remote server url matches the one it actually supports;
- check that for every HTTP request made to the server, the protocol version matches its own expectations.

### Tasks

- [ ] Define and export a `SUPPORTED_PROTOCOL_VERSION` constant defining the protocol version the client actually supports; eg. `export const SUPPORTED_PROTOCOL_VERSION = "v1"`;
- [ ] Ensure the version passed in the `remote` property matches that constant value; raise on mismatch with an appropriate error message;
- [ ] Request server endpoints using that `SUPPORTED_PROTOCOL_VERSION` value;
- [ ] On each request made, check for `404` status code with an `errno` set to `VERSION_NOT_AVAILABLE`; reject with an explicit message in such case;
- [ ] Update docs.

**Comment by leplatrem** [comment]
+1

With a minor comment: the ``404`` can be checked only once at startup while fetching settings.

**Comment by n1k0** [comment]
> With a minor comment: the 404 can be checked only once at startup while fetching settings.

Actually it's no harm to check the status code and presence of the error code on every response received. Or am I missing something? #jet-lag

**Comment by n1k0** [comment]
(that would indeed mean factorize generic response handling to avoid code duplication, obviously)

**Comment by Natim** [comment]
> (that would indeed mean factorizing generic response handling to avoid code duplication, obviously)

Yes that was @leplatrem concern.

**Comment by leplatrem** [comment]
> factorizing generic response handling to avoid code duplication, obviously

**Comment by ametaireau** [comment]
I wonder if we need to actually check the version passed in the URL. Why wouldn't it be possible for `/endpoint/` to support kinto `v1`?

**Comment by Natim** [comment]
This is a good question. For me the answer is convention, because we decided that the way we works with API versionning is using version prefix.

It is part of the protocol, so if somebody tries ``/endpoint/`` instead of ``/v1/`` she is not using kinto v1 protocol.

**Comment by n1k0** [comment]
Good question indeed. I was thinking the prefixing was somewhat part of the protocol. If that's not the case and we want to support custom prefixes (hmm), I can definitely remove that from the spec.

**Comment by n1k0** [comment]
Note that if we `request server endpoints using that `SUPPORTED_PROTOCOL_VERSION` value, we wouldn't match this use case anymore (because we can't predic custom prefixes).

But maybe what we want is to rely on some other mechanism than prefixes to declare the protocol version we actually want to use? Header?

I'm lost all over again ^^'

**Comment by n1k0** [comment]
Fixed.
