### ISSUE TITLE
Fetch remote server settings.

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/kinto.js#41]
### Goals 

The client should retrieve server settings from the `/vX` endpoint; for now, the only setting we need is the `batch_limit one`.

### Tasks

- [ ] On each outgoing HTTP request, first ensure we already have retrieved the settings information;
- [ ] If we haven't yet, request that information from the `/vX` endpoint, then store the settings in a local `Api` property;
- [ ] On subsequent requests, reuse the cached settings property to avoid hammering the server for no reason.

##### Notes

- The implementation shouldn't impact existing documentation;
- Batch limit support should be done along #13, not here.

**Comment by leplatrem** [comment]
+1

*note*: I assume that «*On each outgoing HTTP request*» is a side-effect of factorization, since AFAIK there is no setting implied in polling changes for example.

**Comment by n1k0** [comment]
*Check* is performed on each outgoing request, not *fetch*; we'll cache the settings in a local property, so if it's there already, no need to refetch that information.

**Comment by n1k0** [comment]
Oh I understand what you mean; well, even if we don't need the `batch_limit` value for `fetchChangesSince`, we'll have that already for the obvious next step, which is calling `batch`. Fetching generic settings first makes sense to me, especially as we're likely to use them at any point in the expected use flow.
